services:
  mssql:
    container_name: "webapi_db"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "@Dm1n1234"
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets 
